apiVersion: apps/v1
kind: Deployment
metadata:
  name: marquescgcom
  namespace: default
  labels:
    app: marquescgcom
spec:
  selector:
    matchLabels:
      app: marquescgcom
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: marquescgcom
      labels:
        app: marquescgcom
    spec:
      containers:
        - name: marquescgcom
          imagePullPolicy: Always
          image: marquescg-com
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: gchrio-cred
