apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: tylermarques-com
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dev.u-the-bomb.com`)
      priority: 10
      services:
        - name: dev-tylermarques-com
          port: 3000
