apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      mqtt:
        port: 1883
        protocol: TCP
        expose: true
        exposedPort: 1883