apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarization-worker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diarization-worker
  template:
    metadata:
      labels:
        app: diarization-worker
    spec:
      imagePullSecrets:
        - name: gchrio-cred
      containers:
        - name: diarization-worker
          image: meeting-tools-diarization:latest
          imagePullPolicy: IfNotPresent
          command:
            [
              "celery",
              "-A",
              "tasks",
              "worker",
              "--loglevel=info",
              "--concurrency",
              "1",
              "-Q",
              "process_file"
            ]
          env:
            #Configuration variables
            - name: DATA_DIR
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: data
            - name: CELERY_BROKER_URL
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: rabbitmq
            - name: FASTAPI_URL
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: backendurlinternal
            - name: MODEL_FILE
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: modelfile
            # Secret variables
            - name: HUGGINGFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: meeting-tools-secrets
                  key: huggingface
            - name: INTERFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: meeting-tools-secrets
                  key: interface
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
            - name: model-volume
              mountPath: /app/whisper-models
      volumes:
        - name: data-volume
          nfs:
            server: 192.168.0.71
            path: /main/plex/meeting-tools/prod/data
        - name: model-volume
          nfs:
            server: 192.168.0.71
            path: /main/plex/meeting-tools/prod/whisper-models
      restartPolicy: Always
