apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mealie-db
  namespace: mealie
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17.11-202608170816-standard-trixie@sha256:91e0de662d53895a45f1396f4ee1a75daeb0c26fc87853afc9c8f43e01fdaa21
  affinity:
    nodeSelector:
      kubernetes.io/hostname: k3s-worker-1
  bootstrap:
    initdb:
      dataChecksums: true
      database: mealie
      owner: mealie
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi
  storage:
    size: 10Gi
    storageClass: local-path
