apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: droppedneedle
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: https://github.com/Tylermarques/homelab-infra.git
    targetRevision: main
    path: homecluster/droppedneedle/manifests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=false
