apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysa2mqtt
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: mysa2mqtt
  source:
    repoURL: https://github.com/Tylermarques/homelab-infra.git
    targetRevision: main
    path: homecluster/mysa2mqtt
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
