apiVersion: v1
kind: ConfigMap
metadata:
  name: meeting-tools-config
data:
  backendurl: https://meeting-tools.marquescg.com/dev/api
  backendurlinternal: http://dev-backend-service.meeting-tools.svc.cluster.local:8000
  rabbitmq: amqp://guest:guest@dev-rabbitmq.meeting-tools.svc.cluster.local:5672
  modelfile: /app/whisper-models/ggml-base.en.bin
  data: /app/data
  mongodb: mongodb://dev-mongodb.meeting-tools.svc.cluster.local:27017/dev-meeting-tools
  backendroot: /dev/api
  frontendroot: /dev
