apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: backend
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: dev-meeting-tools-secrets
            - name: INTERFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dev-meeting-tools-secrets
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: diarization-worker-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: diarization-worker
          env:
            - name: INTERFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: dev-meeting-tools-secrets

