apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: freshrss
  namespace: default
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`freshrss.tylermarques.com`)
      priority: 10
      services:
        - name: freshrss
          port: 80
