apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-local
  namespace: homepage
spec:
  secretName: homepage-local-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - home.local.tylermarques.com
