kind: Service
apiVersion: v1
metadata:
  name: marquescg-com
  labels:
    app: marquescg-com
spec:
  ports:
    - name: marquescg-com
      port: 3000
      targetPort: 3000
  selector:
    app: marquescg-com
