apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: immich
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`immich.tylermarques.com`)
      priority: 10
      services:
        - name: immich-server
          port: 2283
  tls:
    secretName: immich-tylermarques-prod-tls

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-tylermarques-com
  namespace: immich
spec:
  secretName: immich-tylermarques-prod-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "immich.tylermarques.com"
  dnsNames:
    - "immich.tylermarques.com"
