env:
  DB_HOSTNAME: "immich-cluster-rw"
  DB_USERNAME:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-userpass
        key: username
  DB_PASSWORD:
    valueFrom:
      secretKeyRef:
        name: immich-postgres-userpass
        key: password

immich:
  persistence:
    library:
      existingClaim: immich-cluster-1

redis:
  enabled: true
  auth:
    enabled: false
