apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: dashy
  namespace: dashy
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`dashy.tylermarques.com`)
      priority: 10
      services:
        - name: dashy
          port: 80
