apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -v
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: transmission-openvpn
  name: transmission-openvpn
spec:
  ports:
    - name: "9091"
      port: 9091
      targetPort: 9091
  selector:
    io.kompose.service: transmission-openvpn
status:
  loadBalancer: {}
