---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: argo-local-tylermarques-com
  namespace: argocd
spec:
  secretName: argocd-local-tylermarques-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: "argocd.local.tylermarques.com"
  dnsNames:
    - "argocd.local.tylermarques.com"
