---
apiVersion: v1
kind: Namespace
metadata:
  name: garage
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: garage-config
  namespace: garage
data:
  garage.toml: |
    metadata_dir = "/data/meta"
    data_dir = "/data/blocks"

    replication_factor = 1

    # RPC secret is loaded from environment variable GARAGE_RPC_SECRET
    # which is set from the garage-secrets Secret

    [rpc_bind_addr]
    rpc_bind_addr = "[::]:3901"
    rpc_public_addr = "garage-rpc.garage.svc.cluster.local:3901"

    [s3_api]
    api_bind_addr = "[::]:3900"
    s3_region = "garage"
    root_domain = ".s3.garage.svc.cluster.local"

    [s3_web]
    bind_addr = "[::]:3902"
    root_domain = ".web.garage.svc.cluster.local"

    [admin]
    api_bind_addr = "[::]:3903"
---
apiVersion: v1
kind: Secret
metadata:
  name: garage-secrets
  namespace: garage
type: Opaque
stringData:
  # Generate with: openssl rand -hex 32
  rpc-secret: "REPLACE_WITH_GENERATED_RPC_SECRET"
  # Generate with: openssl rand -base64 32
  admin-token: "REPLACE_WITH_GENERATED_ADMIN_TOKEN"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: garage
  namespace: garage
spec:
  serviceName: garage
  replicas: 1
  selector:
    matchLabels:
      app: garage
  template:
    metadata:
      labels:
        app: garage
    spec:
      # TODO: Update with actual worker node hostname after attaching disk
      # Get hostname with: kubectl get nodes -o wide
      nodeSelector:
        kubernetes.io/hostname: "REPLACE_WITH_WORKER_NODE_HOSTNAME"
      containers:
        - name: garage
          image: dxflrs/garage:v1.0.1
          ports:
            - name: s3
              containerPort: 3900
              protocol: TCP
            - name: rpc
              containerPort: 3901
              protocol: TCP
            - name: web
              containerPort: 3902
              protocol: TCP
            - name: admin
              containerPort: 3903
              protocol: TCP
          env:
            - name: GARAGE_RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: rpc-secret
            - name: GARAGE_ADMIN_TOKEN
              valueFrom:
                secretKeyRef:
                  name: garage-secrets
                  key: admin-token
          volumeMounts:
            - name: garage-config
              mountPath: /etc/garage.toml
              subPath: garage.toml
            - name: garage-data
              mountPath: /data
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
          livenessProbe:
            httpGet:
              path: /health
              port: admin
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: admin
            initialDelaySeconds: 5
            periodSeconds: 5
      volumes:
        - name: garage-config
          configMap:
            name: garage-config
        - name: garage-data
          hostPath:
            path: /mnt/garage
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: garage-s3
  namespace: garage
spec:
  selector:
    app: garage
  ports:
    - name: s3
      port: 3900
      targetPort: 3900
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: garage-rpc
  namespace: garage
spec:
  selector:
    app: garage
  ports:
    - name: rpc
      port: 3901
      targetPort: 3901
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: garage-admin
  namespace: garage
spec:
  selector:
    app: garage
  ports:
    - name: admin
      port: 3903
      targetPort: 3903
      protocol: TCP
  type: ClusterIP
