apiVersion: v1
kind: ConfigMap
metadata:
  name: meeting-tools-config
data:
  backendurl: http://localhost:8000
  backendurlinternal: http://backend-service.meeting-tools.svc.cluster.local:8000
  rabbitmq: amqp://guest:guest@rabbitmq.meeting-tools.svc.cluster.local:5672
  modelfile: /app/whisper-models/ggml-base.en.bin
  data: /app/data
  mongodb: mongodb://mongodb.meeting-tools.svc.cluster.local:27017/dev-meeting-tools
  backendroot: /api
  frontendroot: /
