apiVersion: apps/v1
kind: Deployment
metadata:
  name: tylermarques-com
  namespace: default
  labels:
    app: tylermarques-com
spec:
  selector:
    matchLabels:
      app: tylermarques-com
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: tylermarques-com
      labels:
        app: tylermarques-com
    spec:
      containers:
        - name: tylermarques-com
          imagePullPolicy: Always
          image: tylermarques-com
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
      imagePullSecrets:
        - name: gchrio-cred
