apiVersion: v1
kind: Service
metadata:
  annotations:
    tailscale.com/tailnet-ip: "100.113.238.46"
  name: proxmox-egress
spec:
  externalName: unused
  type: ExternalName
  ports:
    - name: nfs
      port: 2049
      protocol: TCP
