apiVersion: v1
kind: Pod
metadata:
  name: nfs-test-pod
  namespace: terraria
  annotations:
    tailscale.com/inject: "true"
spec:
  restartPolicy: Never
  containers:
    - name: busybox
      image: busybox
      command:
        - /bin/sh
        - -c
        - |
          echo 'Mounting NFS...';
          mkdir -p /mnt/terraria;
          mount -t nfs -o vers=4 ${NFS_SERVER}:${NFS_PATH} /mnt/nfs;
          echo 'Mount result: $?';
          ls -la /mnt/nfs;
          echo 'Test complete';
          sleep 3600
      env:
        - name: NFS_SERVER
          value: "proxmox-egress"
        - name: NFS_PATH
          value: "/main/plex/"
      securityContext:
        privileged: true
      volumeMounts:
        - name: nfs-csi-volume
          mountPath: /mnt/terraria
  volumes:
    - name: nfs-csi-volume
      persistentVolumeClaim:
        claimName: terraria-pvc
