apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: meeting-tools-backend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            # configuration variables
            - name: DATA_DIR
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: data
            - name: MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: mongodb
            - name: BACKEND_ROOT
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: backendroot
            # secret variables
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: meeting-tools-secrets
                  key: jwt
            - name: INTERFACE_TOKEN
              valueFrom:
                secretKeyRef:
                  name: meeting-tools-secrets
                  key: interface
          volumeMounts:
            - name: data-volume
              mountPath: /app/data
      volumes:
        - name: data-volume
          nfs:
            server: 192.168.0.71
            path: /main/plex/meeting-tools/prod/data
      imagePullSecrets:
        - name: gchrio-cred
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
