apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      imagePullSecrets:
        - name: gchrio-cred
      containers:
        - name: frontend
          image: meeting-tools-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_BACKEND_URL
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: backendurl
            - name: REACT_APP_FRONTEND_ROOT
              valueFrom:
                configMapKeyRef:
                  name: meeting-tools-config
                  key: frontendroot
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: default
spec:
  selector:
    app: frontend
  ports:
    - port: 3000
      targetPort: 3000
