apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  ports:
    - name: http
      port: 32400
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: plex
  namespace: default
subsets:
  - addresses:
      - ip: 192.168.1.89
    ports:
      - name: http
        port: 32400
        protocol: TCP
---
apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: plex
  namespace: default
spec:
  serverName: plex.cd7ff9087f3548f7bc2060dd779a7f78.plex.direct
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: plex-ingress
  namespace: default
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/name: Plex
    gethomepage.dev/group: Media
    gethomepage.dev/icon: plex.png
    gethomepage.dev/href: https://plex.local.tylermarques.com
    gethomepage.dev/external: "true"
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`plex.local.tylermarques.com`)
      services:
        - name: plex
          port: 32400
          scheme: https
          serversTransport: plex
  tls:
    secretName: star-local-tylermarques-prod-tls
