apiVersion: v1
kind: Namespace
metadata:
  name: dashy  
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dashy
  namespace: dashy
spec:
  selector:
    matchLabels:
      app: dashy
  serviceName: dashy
  replicas: 1
  template:
    metadata:
      labels:
        app: dashy
    spec:
      containers:
      - name: dashy
        image: lissy93/dashy
        env:
          - name: BASE_URL
            value: dashy.tylermarques.com
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - mountPath: /app/public/
          name: dashy-config-dir
        livenessProbe:
          exec:
            command:
              - node 
              - /app/services/healthcheck
          initialDelaySeconds: 40
          periodSeconds: 90
          timeoutSeconds: 10
          failureThreshold: 3
      volumes:
      - name: dashy-config-dir 
        nfs:
          path: /main/plex/config/dashy/
          server: 192.168.0.71
---
apiVersion: v1
kind: Service
metadata:
  name: dashy
  namespace: dashy
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: dashy
